Xperience upgraded to 26.1. Application registration changed.
Kentico/xperience-by-kentico-algolia pull request #15
Opened 2023-05-10 13:46 UTC by hesspavel

### Motivation

This PR fixes #`14`

2023-05-10 16:01 UTC, seangwright commented on src/CmsRegistrations.cs
> +//[assembly: UIApplication(typeof(AlgoliaApplication), "Algolia", "{$integrations.algolia.applicationname$}", BaseApplicationCategories.DEVELOPMENT, Icons.Magnifier, TemplateNames.SECTION_LAYOUT)]
We can remove the old overload now?

2023-05-11 08:35 UTC, hesspavel commented on src/CmsRegistrations.cs
> +//[assembly: UIApplication(typeof(AlgoliaApplication), "Algolia", "{$integrations.algolia.applicationname$}", BaseApplicationCategories.DEVELOPMENT, Icons.Magnifier, TemplateNames.SECTION_LAYOUT)]
Done. Thank you for your check.

2023-05-15 11:57 UTC, kentico-jaroslavn requested changes

2023-05-15 11:57 UTC, kentico-jaroslavn commented on src/Kentico.Xperience.Algolia.csproj
> +		<PackageReference Include="Kentico.Xperience.Admin" Version="26.1.1" />
Please increase the version number on line 15 to 2.0.0 as changing the dependency to new major version is considered as breaking change.

2023-05-16 10:55 UTC, kentico-jaroslavn approved these changes

2023-05-16 12:24 UTC, seangwright approved these changes

2023-05-17 05:54 UTC, merged